name = "Twitter"
uuid = "92393bbf-ba23-5323-a3fa-fbe1e5f35af8"
version = "0.8.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OAuth = "22d8b318-f366-56fb-a292-a93f7d76c017"

[compat]
DataFrames = "0.18 - 1"
JSON = "^0.21.0"
OAuth = "^0.7.0"
julia = "^1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
